document.body.style.backgroundColor = "yellow"
let jsp = document.createElement("p");
jsp.textContent = "Hello, world! "
document.body.appendChild(jsp);


for (let i = 0; i < 100; i++) {
    let jsH1 = document.createElement("h1")
    jsH1.textContent = "Hey i got generated by js"
    jsH1.style.color = "blue"
    document.body.appendChild(jsH1);
}

//document.body.removeChild(jsp)

jsp.style.fontSize = "100px"

let existingH1s = document.getElementsByTagName("h1")
existingH1s[0].style.color = "green"
existingH1s[1].style.color = "red"

let jsspan = document.getElementById("spanid")
jsspan.style.color = "purple"
jsspan.textContent = "I am a span"
jsspan.style.fontSize = "100px"
jsspan.style.textDecoration = ("underline")

// let ourSpan= document.getElementsByName("ourSpan")
// ourSpan[0].style.color = "green"
// ourSpan[1].style.color = "red"


// let ourSpan= document.getElementsByName("ourSpan")
// ourSpan[0].style.color = "green"
// ourSpan[1].style.color = "red"


let squarediv = document.getElementsByClassName("square-box");
squarediv[0].innerHTML = "Hello I am a <b> box </b>";

let niceSpanWithId = document.querySelector("#spanid");
niceSpanWithId.style.backgroundColor = "purple";

let divWithclass = document.querySelector(".square-box");
divWithclass.style.backgroundColor = "black";
divWithclass.style.color = "white"


let span= document.querySelectorAll("span")
span[0].style.color = "red"
span[1].style.color = "gold"